name: ğŸš€ Deploy static content to Pages on production

on:
  # main ë¸Œëœì¹˜ë¡œ push í–ˆì„ ë•Œ
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: âœ… Checkout branch
        uses: actions/checkout@v4

      - name: ğŸ“Š Setup nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 18.16.0

      - name: ğŸ¨ Install dependencies
        run: npm ci

      - name: ğŸš€ Build React app
        run: npm run build

      - name: ğŸŒ  configure aws credentials
        uses: aws-actions/configure-aws-crendentials@v2
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region: ap-northeast-2

      - name: ğŸš› Upload to S3
        run: aws s3 sync ./build/ s3://${{ env.S3_BUCKET_NAME }}/
